#!/usr/bin/env php
<?php

if (file_exists(__DIR__.'/../../autoload.php')) {
    require __DIR__.'/../../autoload.php';
} else {
    require __DIR__.'/vendor/autoload.php';
}

$commands = [__DIR__.'/nginx.sh'];
$process = new \Symfony\Component\Process\Process([]);
$app = new Symfony\Component\Console\Application('Larahost Laravel Installer', '1.5.0');
$app->add(new Ankitjain28may\Larahost\LarahostCommand($process, $commands, null));

$app->run();
